### ISSUE TITLE
build_all.bat error

### ISSUE THREAD

**Issue by EdisonB123** [matpow2/anaconda#11]
Every time I run "build_all.bat" I get an error, I run the cmd as an administrator, than navigate to the folder and run as an admin and get this error.

Compiling ./mmfparser/data/chunkloaders/imagebank.pyx because it changed.
Compiling ./mmfparser/bytereader.pyx because it changed.
Compiling ./mmfparser/loader.pyx because it changed.
Compiling ./mmfparser/data/chunk.pyx because it changed.
Compiling ./mmfparser/data/chunkloaders/objectinfo.pyx because it changed.
Compiling ./mmfparser/data/chunkloaders/objects.pyx because it changed.
Compiling ./mmfparser/data/chunkloaders/events.pyx because it changed.
Compiling ./mmfparser/data/chunkloaders/frameitems.pyx because it changed.
Compiling ./mmfparser/data/chunkloaders/expressions/loader.pyx because it change
d.
Compiling ./mmfparser/data/chunkloaders/expressions/loaders.pyx because it chang
ed.
Compiling ./mmfparser/data/chunkloaders/common.pyx because it changed.
Compiling ./mmfparser/data/onepointfive.pyx because it changed.
Compiling ./mmfparser/image.pyx because it changed.
Compiling ./mmfparser/texpack.pyx because it changed.
Compiling ./mmfparser/gperf.pyx because it changed.
Cythonizing ./mmfparser/bytereader.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        if self.fp != NULL:
            self.seek(self.tell() + value)
        else:
            self.pos += value

    cdef bint _read(self, void * value, int size):
        ^
------------------------------------------------------------

mmfparser\bytereader.pyx:144:9: Signature not compatible with previous declarati
on

Error compiling Cython file:
------------------------------------------------------------
...
    cpdef ByteReader readReader(self, size_t size)
    cpdef bint write(self, bytes data)
    cpdef bint write_size(self, char * data, size_t size)
    cpdef bint skipBytes(self, size_t n)
    cpdef bint rewind(self, size_t n)
    cdef bint _read(self, void * value, int size) except False
^
------------------------------------------------------------

mmfparser\bytereader.pxd:47:19: Previous declaration is here
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    ext_modules = cythonize(ext_modules)
  File "C:\Python27\lib\site-packages\Cython\Build\Dependencies.py", line 865, i
n cythonize
    cythonize_one(*args[1:])
  File "C:\Python27\lib\site-packages\Cython\Build\Dependencies.py", line 985, i
n cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: ./mmfparser/bytereader.pyx

**Comment by matpow2** [comment]
This was fixed in trunk.
