### ISSUE TITLE
Help ! (Please)

### ISSUE THREAD

**Issue by iQuintennn** [matpow2/anaconda#12]
Hello i have made a game, and i cant recover it thats why i downladed anaconda. but i constantly get an error "Import error: No Module Named Loader" please help ;) -Quinten

**Comment by matpow2** [comment]
http://mp2.dk/ss/9C4cpZL.png

My guess is that you're trying to decompile FNAF.
That's not what the tool is for.

**Comment by smarbrand** [comment]
WTF is wrong with you, its his game, he made a fnaf fangame and not fnaf

**Comment by smarbrand** [comment]
Quintennn run Build_all that should fix it

**Comment by iQuintennn** [comment]
Well i am not.

**Comment by freddle1** [comment]
um... the fuck does fnaf have to do with this? also @iQuintennn you have to run build_all
