### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by smarbrand** [matpow2/anaconda#14]
Everytime i try to decompile my Game, it says Exception: unsupported compression flag!

**Comment by matpow2** [comment]
http://mp2.dk/ss/F27XvVZ.png

Maybe you shouldn't be decompiling FNAF3.

**Comment by smarbrand** [comment]
i didn't decompile fnaf, only cause i like fnaf does it mean i decompile it

**Comment by matpow2** [comment]
Please upload the EXE of your game then.

**Comment by smarbrand** [comment]
Why? what should that bring?

**Comment by matpow2** [comment]
I can't reproduce the issue here on my own executables, so you will have to upload an EXE of your game.

**Comment by smarbrand** [comment]
First tell me, why does this happen then i will upload it

**Comment by matpow2** [comment]
It could be anything. I'm only asking for a reproducible case - is it hard to reproduce?

**Comment by smarbrand** [comment]
maybe you can start with unsupported compression flag: 3, downloaded the new version
