### ISSUE TITLE
Support for new compression format

### ISSUE THREAD

**Issue by HimeWorks** [matpow2/anaconda#17]
Hello,

Previously, MMF appeared to only use deflate as the the primary form of compression, but when I checked some files recently it looks like there's a new method being used in addition to deflate.

Does/will Anaconda support the new method?

Thanks

**Comment by matpow2** [comment]
Install the Chowdren exporter plugin and export as a Chowdren CCN if you want to use chowdren.run directly. Out of curiosity, what is this for?

**Comment by HimeWorks** [comment]
I've received a request for decompiling some game files and was informed that your programs should be able to do the trick.

**Comment by matpow2** [comment]
That sounds very vague, and I'm vary of people seeking to decompile games they are not the author of.
Please post the files here.

**Comment by HimeWorks** [comment]
These files don't look like their own work. I will refrain from posting them. Thanks for your time.
