### ISSUE TITLE
Unsupported Compression Tag: 3

### ISSUE THREAD

**Issue by FateForWindows** [matpow2/anaconda#20]
I'm sure you've gotten requests to add this in. I created a FNAF fan game called [The Five Nights: Fredbear](http://gamejolt.com/games/the-five-nights-fredbear/76871), and I'd like to decompile an older version. It was the third demo I released with two nights for the game (I've made 2 demos since), but when you try starting a night, it loads, but when it attempts to begin the night, it goes back to the load frame. I figured out what the problem was (I forgot to set the group for the .ini object), and I'd like to show people what it was like. Sadly, I can't decompile the game to fix the issue, because of an error I get: Unsupported Compression Tag: 3. Can you please fix this?

**Comment by matpow2** [comment]
Or maybe you shouldn't be decompiling FNAF.

**Comment by FateForWindows** [comment]
I'm not decompiling FNAF, I'm decompiling a version of MY OWN FNAF FANGAME!!!

**Comment by matpow2** [comment]
Would you believe me if I told you I've heard that one before? ;-)

**Comment by FateForWindows** [comment]
BUT IT'S MY OWN FANGAME!!!!!!!!!!!!!!!!

**Comment by FateForWindows** [comment]
I WANT TO DECOMPILE THAT

**Comment by FateForWindows** [comment]
Fine. I won't release it again.

**Comment by FateForWindows** [comment]
Did you think I was kidding? I don't stop giving up when I have something important to do, especially trying to decompile my fangame.

**Comment by matpow2** [comment]
OK, you're getting the banhammer.

**Comment by freddle1** [comment]
Wow.... -_- @matpow2 he was actually not decompiling fnaf... this is just sad. @FateForWindows were you able to decompile your game? if so I wanna play it :)
