### ISSUE TITLE
textures not loading

### ISSUE THREAD

**Issue by topkeksphagetti** [matpow2/anaconda#22]
When trying to decompile my own applications, I get all of my frames loaded correctly with all objects and events intact except for the textures, keep in mind I had to edit some files to make the unsupported compression tag 3 be supported. My issue is that I get corrupted blocks instead of the actual textures

**Comment by topkeksphagetti** [comment]
my issue is that I get corrupted blocks instead of the actual

**Comment by matpow2** [comment]
Can you send the application in question?

**Comment by topkeksphagetti** [comment]
here http://www.mediafire.com/download/xjagxar00tlj2en/not_an_average_arcade_game.exe

**Comment by matpow2** [comment]
F2.5 is not supported.

**Comment by topkeksphagetti** [comment]
when will it be supported?

**Comment by topkeksphagetti** [comment]
extra note: I had to use this git checkout 5d630cb0903badbbb886d40e93dba706e26cc85c

**Comment by topkeksphagetti** [comment]
nevermind I fixed the issue

**Comment by freddle1** [comment]
um....... F2.5 is supported. You have to patch a file
