### ISSUE TITLE
Unsupported Compression flag: 3

### ISSUE THREAD

**Issue by Apollo8YT** [matpow2/anaconda#23]
Hi, i try to decompile another game [No fnaf3], and this have this error do you have a answer about this?
PD: i Speak Spanish :3

**Comment by matpow2** [comment]
Sigh. No.

http://mp2.dk/ss/Y9CZhln.png

**Comment by topkeksphagetti** [comment]
Apollo8YT, why can't you just fix it yourself? anaconda is really easy to edit and I managed to fix the error and the texture problem!

**Comment by freddle1** [comment]
wow... what does that screenshot have to do with anything? it's just fnaf...

**Comment by freddle1** [comment]
@Apollo8YT send me your EXE and imma send you a MFA lol
