### ISSUE TITLE
I kinda feel like shitposting but this needs to be said, lol

### ISSUE THREAD

**Issue by pete7201** [matpow2/anaconda#24]
matpow2, 
I actually made a github acc just so I could post this, it's important enough for that :P
So anyway I was looking at a lot of the closed issues, old commits, and apparently FNAF is an issue or something? Apparently you think lots of people are going to decompile this game, when in reality you need to wake up and realize 2 things, 1) just because somebody likes a game does not mean they are going to try to mess with its code, and 2) most all of the people that are having issues with "compression tag 3" are legit trying to decompile their OWN games. 
Also bonus 3) the FNAF community "abuses" this tool due to the nature of FNAF. Clearly you haven't played it. I have a fucking lot of MMF games, and I only decompiled the fnaf series and one other because of the cryptic nature of said games.

Sorry I sounded like a dick, but this needed to be said. Don't even bother looking if I am involved with FNAF. I like the series and the MFAs are on my website. Maybe this opened your eyes to why the fnaf community loves decompiling, it's not to pirate games, as you could just distribute the EXE ;)

Also, I'm not asking for help/trying to get the source for any game, I have a working build 284 decompiler and I can decompile basically any (good!) application out there ;)

-pete7201

**Comment by pete7201** [comment]
This just had to be said, I'm sorry :P lol
if anybody wants their not FNAF compression tag: 3 game decompiled send me a link to your exe and I will send you a MFA lol

**Comment by matpow2** [comment]
Whatever, don't decompile games that aren't your own.

**Comment by pete7201** [comment]
I only really got into this because I saw what happened to a lot of people such as FateForWindows. someone from /r/technicalFNAF had to decompile his game for him because apparently he was decompiling FNAF3

funny thing is, there's no need to do that when you can just download the mfas from my server lol
